# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog Worx v2
email: sash@binary.com
description: > # this means to ignore newlines until "baseurl:"
  Binary.com is the premier trading platform for binary options on all financial markets. Trade Forex, Indices, Stocks, Commodities and global Sector Indices with trades ranging from 15 seconds up to 365 days.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
paginate: 10